# Generated by Django 4.2.17 on 2025-01-22 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_videomeeting_videomeetingrecording_studentgroup_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='max_points',
            field=models.IntegerField(default=100),
        ),
    ]
