# Generated by Django 4.2.17 on 2025-01-22 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_quiz_max_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='videomeeting',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
